### PR TITLE
Hierarchical Search

### PR DESCRIPTION
**Pull request by mshubhankar**
Implementation to figure 11.5 Hierarchical Search and Refinements function.
Issue #35

### CODE REVIEW

**Comment by ctjoreilly** [comment]
A nice start. Could you add JUnit tests that demonstrate the functioning of the implemented algorithm.

Thanks

**Comment by mshubhankar** [comment]
Hill Climbing Search doesn't have a JUnit test case in the same folder. That is the reason why i didn't write a test for this. Is there a reason why it doesnt have a JUnit case ?

**Comment by norvig** [comment]
This is nice work -- I'd love to see it finished up.

**Comment by ctjoreilly** [comment]
Closing due to lack of further progress.

**Pull request closed without merging**
