### PR TITLE
Aima4e - AIMA4e reimplement Fig 5.3 Minimax-Decision from AIMA3e branch 

### PR DESCRIPTION
**Pull request by tmt96**
I gave the issue a try the last few days. Not many changes from what we have in AIMA3e though. I haven't written tests yet, so I hope to find some suggestions.

### CODE REVIEW

**Comment by smsubham** [comment]
Hi
Just had a brief look at your code , it seems good. Could you please add more documentation to functions in MinimaxSearch.java.
Moreover , in MinimaxSearch.java documentation "Artificial Intelligence A Modern Approach (3rd Edition): page 169"
should be changed to Artificial Intelligence A Modern Approach (4th Edition): Figure ?? page ?? , as you are coding in AIMA4e branch and we don't know page no and figure no for 4th Edition of this book.

Thanks
Subham

**Comment by smsubham** [comment]
Hi
Just had a brief look at your code , it seems good but i would like you to note that in AIMA4e branch implementation of some packages you are importing have changed from that of AIMA3e branch. So you should code for AIMA4e branch keeping these changes in mind. 
In MinimaxSearch.java documentation "Artificial Intelligence A Modern Approach (3rd Edition): page 169" should be changed to Artificial Intelligence A Modern Approach (4th Edition): Figure ?? page ?? , as you are coding in AIMA4e branch and we don't know page no and figure no for 4th Edition of this book.
Moreover , Could you please add more documentation to functions in MinimaxSearch.java.

Thanks
Subham

**Comment by tmt96** [comment]
Hi Subham, thanks for the feedback. I noticed that the interface Action has been removed from the AIMA4e branch in favor of generic types so I have changed my code accordingly. Would love to hear further feedbacks from anyone.

**Comment by smsubham** [comment]
Ya it's changed to provide clean UI  and it has made code easier to understand. After making necessary changes submit a pull request.

Regards
Subham

**Comment by ctjoreilly** [comment]
Have taken a slightly different approach based on latest APIs in aima4e.

**Pull request closed without merging**
