### PR TITLE
Add HillClimbingSearchWithSidewaysMoves.java

### PR DESCRIPTION
**Pull request by ritwik12**
I am adding HillClimbingSearchWithSidewaysMoves.java from AIMA4e for the issue #357 
The code was originally written by Ciaran O'Reilly.
I think this code is important as SidewaysMoves are very helpful in a case of a Plateaux/shoulder.

### CODE REVIEW

**Comment by utsavoza** [comment]
I am unsure of how all the checks have passed successfully for this PR. I suppose `ant aima-core.test-all` in `.travis.yml` currently validates only changes made to `aima-core`. As for the changes are concerned, the implementation doesn't comply with the search api in AIMA3e branch. I'd rather accompany the implementation with a unit test to be sure of the changes made to a specific branch.

**Comment by ritwik12** [comment]
I have reimplemented the code from AIMA4e branch and up to my knowledge that code works well.
Can you please elaborate what you are suggesting?

**Comment by ritwik12** [comment]
@norvig Please have a look

**Review by samagra14 — CHANGES_REQUESTED** [review]
The absence of appropriate tests is disturbing. Please add them.

**Comment by norvig** [comment]
The implementation is faulty and there are no test cases. Besides, there is no requirement of Hill Climbing with sideways moves as far as AIMA3e is concerned.

**Pull request closed without merging**
