### PR TITLE
Add DT-Agent in readme.md for AIMA4e

### PR DESCRIPTION
**Pull request by ritwik12**

### CODE REVIEW

**Review by samagra14 — APPROVED** [review]

**Comment by samagra14** [comment]
Just have a look at the conflicts @ritwik12.

**Comment by ritwik12** [comment]
@samagra14 Corrected, thanks for the nudge

**Comment by ritwik12** [comment]
@norvig Please have a look!!

**Comment by samagra14** [comment]
@norvig This PR can be merged.

**Pull request merged**
