### PR TITLE
Corrected OnlineSearchProblem.java link

### PR DESCRIPTION
**Pull request by ritwik12**
No file exists with this name in the specified directory.

### CODE REVIEW

**Comment by utsavoza** [comment]
The file exists (under `package aima.core.search.framework.problem`), but its entry is incorrectly linked in the README.md. Do you mind correcting the link and resending the patch?

**Comment by ritwik12** [comment]
@utsavoza Yes, let me correct it. Thanks !!

**Comment by utsavoza** [comment]
If you look closely, the links to other files in README.md are relative links. GitHub automatically transforms those relative link in the README.md to absolute links, so that the link or path always work irrespective of changes in the GItHub API. Absolute links however, may not work in the clones of the repository.

**Comment by ritwik12** [comment]
@utsavoza But that file was not even at that place. I have corrected it now.

**Comment by ritwik12** [comment]
Corrected

**Comment by utsavoza** [comment]
Can you squash the commits into one as all the commits relate to a single change?

**Pull request closed without merging**
