### PR TITLE
Create GRAPHPLAN.java

### PR DESCRIPTION
**Pull request by smsubham**
Have tried to implement Figure 10.9 The GRAPHPLAN algorithm. Have kept function used in it in abstract form , as same was done for KB-Agent and some other implementation. Is it ok or do i need to explicitly implement it?
Update- Will be adding Junit Test cases soon.

### CODE REVIEW

**Comment by anurag-rai** [comment]
@smsubham Are you planning to create a base class for this to implement the abstract methods, or are you leaving that up to the user? Also, a Unit Test can be helpful here to demonstrate the working of the algo.

**Comment by smsubham** [comment]
Hi
Look at https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/main/java/aima/core/logic/propositional/agent/KBAgent.java 
In this implementation of KBAgent , class is kept abstract and no JUnit test cases are also written for it i suppose. 
I already know about Unit test  and its usefulness to demonstrate how things works in an algo.
All i want to know from @ctjoreilly sir , is it ok to keep this implementation abstract for now or should i implement those abstract methods also. 
Thanks for trying to help @anurag-rai .

**Comment by ctjoreilly** [comment]
Hi,

In the case of GraphPlan I think you should be able to create a concrete implementation and test it out.

Thanks

Ciaran

**Comment by smsubham** [comment]
Ok sir thanks for clarifying. Am working on it. Will be adding abstract methods implementation and Unit test for it soon.

**Comment by ctjoreilly** [comment]
This is a mixed pull request, closing in preference of receiving a more concrete implementation.

**Pull request closed without merging**
