### PR TITLE
Add support for complex actions

### PR DESCRIPTION
**Pull request by Manthan-R-Sheth**
The method of reversing and adding to the list is changed to support complex actions in the problem.
1. ```fromMeetingStateToInitialStateList``` and ```fromMeetingStateToGoalStateList``` are made to achieve the purpose.
1. InitialState and GoalState are included in the fromGoalStateToInitialState and fromInitialStateToGoalState respectively.

### CODE REVIEW

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly Fixes #298

**Comment by ctjoreilly** [comment]
Hi,

Could you update this with respect to the recent changes from pull request #308. Also, please ensure you squash/rebase as needed.

Thanks

Ciaran

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly 
The implementation in #308 increases complexity of the whole algorithm (as an additional O(n) algorithm is used to find the meeting node). Though other changes i.e. name changes and addition of test cases are fine, the changes in ```BidirectionalSearch``` aren't (Correct me if I am wrong). 
Moreover after this PR (#304) is included in the main code, same results are obtained as that in #308 and with the null checks, all would be good to go.

**Comment by ctjoreilly** [comment]
Hi @Manthan-R-Sheth and @globalworming,

I have moved and renamed BidrectionalSearch from the core to extra module under:

aima.extra.search.uninformed.BidirectionalSearchGW

@Manthan-R-Sheth I am going to close this pull request but could you do the following:
- Add your version of BidrectionalSearch to aima.extra.search.uninformed.BidirectionalSearchMRS
- Update BidirectionalSearchTest to include "BidirectionalSearchMRS" as  searchFunctionName and the searchForActions() method is updated to instantiate it correctly. You version needs to pass all the current tests.
- Update the README.md to include a link to your version of the algorithm (I have added a TODO in there for you).
- Do not modify any of the core code with this pull request - i.e. BasicBidirectionalSearchResult, SearchForActionsBidirectionallyFunction, etc... should remain untouched.

My rationale for this re-org is as follows:
1. Neither implementation belongs within the core module as they do not reflect what is currently outlined in: https://github.com/aimacode/aima-pseudocode/issues/41. In particular as it is an informed (i.e. heuristic) based algorithm that is described.

2. Due to 1 my focus has not been on the current implementations that have been submitted but on the API. 

3. I appreciate both your efforts and think it good/healthy to place both alternative methods in the 'extra' module so their relative trade offs can be compared more easily side by side.

Thanks

Ciaran

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly 
This sounds logical :+1:  and I shall do the required in the upcoming PR.

**Pull request closed without merging**
