### PR TITLE
Add Environment.java to AIMA4e

### PR DESCRIPTION
**Pull request by ritwik12**
This PR consists :   
1. Add Environment in README.md.
2. Add Environment.java.

### CODE REVIEW

**Comment by ritwik12** [comment]
solves issue #371

**Comment by okulev** [comment]
The JavaDoc comments in 0229025 are incorrectly placed.

**Comment by ritwik12** [comment]
Sorry, @okulev  I am not able to understand. Can you please point out the improvement?

**Comment by okulev** [comment]
The JavaDoc comment of addAgent method should be JavaDoc for getAgents. JavaDoc of removeAgent should be moved to addAgent, and so on.

**Comment by ritwik12** [comment]
Thanks, @okulev  for the correction. I corrected it

**Pull request closed without merging**
