### PR TITLE
Adds contributing guidelines

### PR DESCRIPTION
**Pull request by samagra14**
@norvig Please have a look at these contribution guidelines. I have tried to be as specific as possible. Do let me know if there is anything else that can be added.

### CODE REVIEW

**Comment by ritwik12** [comment]
@samagra14 Looks good!!

**Comment by norvig** [comment]
The commit messages, `:racehorse`, etc. seem strange to me. Is there established practice to using these names? I don't think I could memorize them, and most of them I wouldn't recognize when I read them, unless I went back and looked at the key.

**Comment by samagra14** [comment]
These instructions were mutual to many popular FOSS projects and therefore I included them. Those commit messages are optional and can be used to increase the readability of the commits. These can be removed if necessary.

**Comment by norvig** [comment]
If these are common, then we should leave them in. They are just new to me.

**Pull request merged**
