### PR TITLE
Update  FOL-BC-Ask Java Doc

### PR DESCRIPTION
**Pull request by ritwik12**
#51 Updating Java Doc according to AIMA 3rd edition. Previously Java doc was according to AIMA 2nd edition.

### CODE REVIEW

**Comment by ritwik12** [comment]
@norvig please have a look.

**Review by samagra14 — COMMENTED** [review]
I think the Java Doc must be updated only if the implementation is updated to match the AIMA3e version.
Currently, the implementation is not as per the 3rd edition. So the Javadoc must remain consistent with the existing code. You must re-implement the algorithm along with updating the JavaDoc changes.

**Comment by ritwik12** [comment]
@samagra14 That is why I have only made changes to the text which doesn't have to do anything with implementation. I agree with you. I did this as It was not looking good due to old doc. rest is on Collaborators.

**Comment by ritwik12** [comment]
@samagra14 I will try to reimplement it too.

**Pull request merged**
