### PR TITLE
issue #193 18.8 Cross Validation Wrapper implementation 

### PR DESCRIPTION
**Pull request by Allen-Hao-Huang**
CrossValidationWrapper() is not guaranteed to terminate as the psuedo code is from 1 to inf

Check for convergence is checking if 2 values are very close to each other, however it still might not mean it has converged

### CODE REVIEW

**Comment by ctjoreilly** [comment]
Hi,

This is a good start. I would ask that you review the general guidelines here:

https://github.com/aimacode/aima-java/wiki/AIMAJava-Contributing

In particular, could you:

1. Include JUnit tests demonstrating the algorithm working (should run quickly, can just be simple example).
2. Include JavaDoc pseudocode of the algorithm in the class comment block, see:

https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/main/java/aima/core/environment/vacuum/ReflexVacuumAgent.java

for an example.

As regards the not guaranteed to terminate, that is fine, this is just intended to be a simple example and adding a NOTE at the bottom of the class javadoc highlighting this is sufficient (addressing it can be done by with an alternative implementation that addresses/improves upon the pseudocode but that should be a separate submission).

Thanks

Ciaran

**Comment by Allen-Hao-Huang** [comment]
thanks for the feedback! I will try get it done soon

**Comment by Allen-Hao-Huang** [comment]
@ctjoreilly currently writing JUnit tests with a polynomial regression model as the learner, how would you store paired data values into the class Example for the dataset? is targetValue() inside Example.java supposed to return a value from attributes?

**Comment by ctjoreilly** [comment]
Have a look at DataSetFactory.getIrisDataSet(), this creates a dataset from file with numeric attributes. I think this should be close to what you need. Also, did you intentionally close this issue?

**Comment by Allen-Hao-Huang** [comment]
@ctjoreilly issue 43/193 is still there, i don't think i closed the issue? This was a pull request and i closed it because i'm writing the JUnit tests

**Pull request closed without merging**
