### PR TITLE
Implementation of Online-DFS-Agent #132

### PR DESCRIPTION
**Pull request by anurag-rai**
Addresses and completely solves Issue #132 
A data-structure (`Two-key Hash-Map`) from the 3e branch has been utilized.
The Test Suite is a little lengthy as I didn't re-implement the `Map` and `Environment`classes, and it works for all different cases like:
- Working of the Class
- If Already at Goal State
- If No Path to Goal State
- A Normal Search
- Testing the Cases of Fig. 4.19 from the Book (3rd Edition)

P.S. I have used my own implementation of `OnlineSearchProblem` #131 which I've resolved in #147 
This is a further branch.

### CODE REVIEW

**Comment by anurag-rai** [comment]
I was getting a `java.lang.VerifyError` and it was difficult to pin-point the dependency that was causing it. It was running fine in my system, but was failing over here. Finally managed to figure it out though.

**Comment by ctjoreilly** [comment]
@anurag-rai out of curiosity what was the cause of the java.lang.VerifyError?

Does this push request overlap with #131 ?

**Comment by anurag-rai** [comment]
@ctjoreilly In the J-unit Test class, I was declaring my `Graph`, `Actions-Function` and `Goal-Test-Function` inside the `Test` method, which threw the `java.lang.VerifyError`. As soon as I moved them out of the method and declared them as global, the error was resolved. Although, I didn't really understand the concept behind this.
The tests are working though. I've checked a lot of edge cases, scenarios and have run an example from the book too.

And yes, this push does overlap with #131 as the classes were needed.

[I've however sent a separate pull request(#147) for #131 alone as well]

**Comment by ctjoreilly** [comment]
Have cherry picked code for inclusion in aima4e.

**Pull request closed without merging**
