### PR TITLE
Re-implementation of RewardFunction.java to incorporate Java 8 features

### PR DESCRIPTION
**Pull request by damnOblivious**
Re-implemented RewardFunction.java 
to incorporate
Java8 features:functional interfaces and lambda expressions

### CODE REVIEW

**Comment by damnOblivious** [comment]
@ctjoreilly  @RuedigerLunde 
Please review this PR and let me know if you want changes in the PR.

**Comment by samagra14** [comment]
@guptavaibhav18197 I guess Java8 related changes are to be incorporated in the AIMA4e branch. I guess it would be better if you redirect this pull request to the AIMA4e branch. Please wait for the official word.

**Comment by damnOblivious** [comment]
@samagra14 yes, after making the PR I noticed the same. But I am not able to make changes in 4e branch. There are not configuration files for IDE(in my case, I am using Intellij) so I am not able to switch branch to 4e. 
Do you know how can we contribute to 4e branch?

**Comment by samagra14** [comment]
@guptavaibhav18197 Please go through [these instructions](https://github.com/aimacode/aima-java/wiki/AIMA4e-Using-IntelliJ-IDEA).

**Comment by damnOblivious** [comment]
@samagra14 thanks for the link

**Pull request merged**
