### PR TITLE
Aima4e reimplement fig 5.3 minimax decision from aima3e

### PR DESCRIPTION
**Pull request by smsubham**
Complete solution of #134 
Test cases require implementation of interface
Have improved documentation and added generics support.
@ctjoreilly

### CODE REVIEW

**Comment by smsubham** [comment]
By mistake extra classes are added , fixed it.

**Comment by anurag-rai** [comment]
@smsubham There is already a PR #209 for this issue. Is it overlapping or solving something else?

**Comment by smsubham** [comment]
Am aware of PR #209. Have provided feedback on it too. As i wasn't satisfied with his changes tried to implement it myself. Have added support for generics , improved documentation. 
@anurag-rai

**Comment by ctjoreilly** [comment]
Have taken a slightly different approach on the aima4e implementation.

**Pull request closed without merging**
